site_name: Портфолио лабораторных работ
site_description: Сайт-портфолио студента
site_author: Родина Виктория

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search