docs_dir: source # Где искать исходные .md файлы
site_name: Портфолио лабораторных работ
site_description: Сайт-портфолио студента
site_author: Родина Виктория

theme:
  name: material
  language: ru

  # НАСТРОЙКА ЦВЕТОВ
  palette:
    # Светлая тема (бело-изумрудная)
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему

    # Темная тема
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

  # Дополнительные функции
  features:
    - navigation.tabs  # Вкладки в навигации
    - navigation.sections # Секции в меню
    - navigation.top # Кнопка "наверх"
    - search.suggest # Подсказки в поиске
    - search.highlight # Подсветка результатов
    - content.code.copy # Кнопка копирования кода

# Навигация
nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Лабораторная работа №1: labs/lab1.md
    - Лабораторная работа №2: labs/lab2.md
    - Лабораторная работа №3: labs/lab3.md
    - Лабораторная работа №4: labs/lab4.md
    - Лабораторная работа №5: labs/lab5.md

plugins:
  - search